version: '3'

services:
  tfserving:
    image: tensorflow/serving:nightly
    ports:
      - "8501:8501"
      - "8500:8500"
    restart: unless-stopped
    #    environment:
    #      - TF_CPP_MIN_VLOG_LEVEL=1
    volumes:
      - ./models.config:/models.conf
      - ./models:/models
    command: --model_config_file=/models.conf